name: S-Core
version: '1.0'
main: dev.losterixx.sCore.paper.PaperMain
api-version: '1.21'
authors: [ Losterixx ]
description: -/-
softdepend:
  - PlaceholderAPI
  - Nexo
commands:
  sCore:
    description: Main plugin command
    aliases:
      - sc
  setspawn:
    description: Set the server spawn
  spawn:
    description: Teleport to the server spawn
  broadcast:
    description: Broadcast messages
  invsee:
    description: Show/Modify other players inventory
    aliases:
      - invs
  endersee:
    description: Show/Modify other players enderchest
    aliases:
      - enders
      - ecsee
  extrasee:
    description: Show/Modify other players extra items
    aliases:
      - armorsee
      - equipsee
  setwarp:
    description: Set a warp
  warp:
    description: Warp to a location
  delwarp:
    description: Delete a warp
  listwarps:
    description: List all warps
    aliases:
      - warps
permissions:
  "sCore.admin":
    description: Permission to access plugin main command
    default: op
  "sCore.command.setspawn":
    description: Permission to set the server spawn
    default: op
  "sCore.command.spawn":
    description: Permission to teleport to the server spawn
    default: op
  "sCore.command.broadcast":
    description: Permission to broadcast messages
    default: op
  "sCore.command.invsee.show":
    description: Permission to show other players inventory
    default: op
  "sCore.command.invsee.modify":
    description: Permission to modify other players inventory
    default: op
  "sCore.command.endersee.show":
    description: Permission to show other players enderchest
    default: op
  "sCore.command.endersee.modify":
    description: Permission to modify other players enderchest
    default: op
  "sCore.command.extrasee.show":
    description: Permission to show other players extra items
    default: op
  "sCore.command.extrasee.modify":
    description: Permission to modify other players extra items
    default: op
  "sCore.command.setwarp":
    description: Permission to set a warp
    default: op
  "sCore.command.delwarp":
    description: Permission to delete a warp
    default: op
  "sCore.command.warp":
    description: Permission to teleport to a warp
    default: op
  "sCore.command.listwarps":
    description: Permission to list all warps
    default: op